# Icons Registry Reference
# This file is used as a reference so that future developers and AI assistants
# do not forget the mapping between emojis and graphic icons used in the DOM.

ICON_MAPPINGS = {
    "🔒": "lock.png",
    "🔓": "unlock.png",
    "ℹ️": "info.png",
    "📁": "folder.png",
    "📂": "folder-open.png",
    "🖼️": "image.png",
    "🎬": "video.png",
    "🎵": "audio.png",
    "📄": "file.png",
    "⚠️": "warning.png",
    "☀️": "sun.png",
    "🌙": "moon.png",
    "🖥️": "display.png",
    "🐍": "python.png",
    "❔": "question.png",
    "⚙️": "info.png",
    "▶️": "ui-button.png",
    "📋": "clipboard.png",
    "✅": "checkmark.png",
    "📺": "tv.png",
    "🔊": "speaker.png",
    "🧩": "puzzle.png",
    # Zone / wave / timeline additions (font-rendered 256x256 RGBA).
    # Keys are the base chars; ui.js matches base and VS16 forms of each.
    "⏮": "prev.png",
    "⏱": "stopwatch.png",
    "⏳": "hourglass.png",
    "⏸": "pause.png",
    "⚡": "bolt.png",
    "✋": "hand.png",
    "✕": "close.png",
    "❌": "cross.png",
    "➕": "plus.png",
    "⬆": "arrow-up.png",
    "⬇": "arrow-down.png",
    "🌊": "wave.png",
    "🎨": "palette.png",
    "🎯": "target.png",
    "💡": "bulb.png",
    "💾": "save.png",
    "📊": "chart.png",
    "📍": "pin.png",
    "📐": "ruler.png",
    "📥": "inbox.png",
    "📦": "package.png",
    "📱": "phone.png",
    "📷": "camera.png",
    "🔄": "refresh.png",
    "🔍": "search.png",
    "🔲": "full-frame.png",
    "🗑": "trash.png",
    "🗜": "compress.png",
    "🟩": "green-square.png",
    "🧹": "broom.png",
    "🩹": "bandage.png",
}
